### ISSUE TITLE
Run directory clean up fails then xdg-dbus-proxy is called with incorrect arguments 

### ISSUE THREAD

**Issue by igo95862** [igo95862/bubblejail#100]
### Output of `bubblejail --version`

AUR-git 0.8.3.r529.9ffbc0a

### Your distro name and version

Arch Linux

### Description

Exception trace:

```
'--own=com.steampowered' is not a valid dbus name
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 20, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 230, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 98, in run_bjail
    async_run(
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 227, in async_run_init
    async with runner:
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_runner.py", line 427, in __aenter__
    await self.setup_dbus_proxy()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_runner.py", line 335, in setup_dbus_proxy
    await wait_for(dbus_proxy_ready_future, timeout=1)
  File "/usr/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
```

**Comment by igo95862** [comment]
Fixed in 61a74126b47649fd0496d883a61b671f8db33aa4
