### ISSUE TITLE
Arch Linux - test.test_instance_creation fails in chroot build

### ISSUE THREAD

**Issue by kiasoc5** [igo95862/bubblejail#12]
bubblejail-0.4.2-1-x86_64-build.log when built with `aur build -c`
```
ninja: Entering directory `/build/bubblejail/src/build'
ninja: no work to do.
1/1 unittest FAIL            0.14s   exit status 1
>>> MALLOC_PERTURB_=9 /usr/bin/python3 -m unittest
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
Started unix server
self.terminator_look_for_command:  None
Client connected
Response bytes: b'{"id": "test", "result": ["pong"]}\n'
Terminated
Reached end of reader. Returnning
stderr:
./build/bubblejail/src/test/test_helper.py:35: DeprecationWarning: There is no current event loop
  self.event_loop = get_event_loop()
..E...
======================================================================
ERROR: test.test_instance_creation (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_instance_creation
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/build/bubblejail/src/test/test_instance_creation.py", line 24, in <module>
    from bubblejail.bubblejail_directories import BubblejailDirectories
  File "/build/bubblejail/src/bubblejail/bubblejail_directories.py", line 38, in <module>
    UserConfigDir.mkdir(exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1173, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/build/.config/bubblejail'


----------------------------------------------------------------------
Ran 7 tests in 0.016s

FAILED (errors=1)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

1/1 unittest FAIL            0.14s   exit status 1


Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /build/bubblejail/src/build/meson-logs/testlog.txt
[1m[31m==> ERROR:(B[m[1m A failure occurred in check().(B[m
[1m    Aborting...(B[m
```

**Comment by igo95862** [comment]
The issue is that the `${XDG_CONFIG_DIR}/bubblejail` gets created when a module is loaded without creating the parents.

https://github.com/igo95862/bubblejail/blob/7276e0d5baed70473f7b31aa97b8750782817f61/bubblejail/bubblejail_directories.py#L38

I think that loading modules by itself should not have side effects. I will see if I can fix that.

**Comment by igo95862** [comment]
@kiasoc5 See if it works now.

**Comment by kiasoc5** [comment]
@igo95862 it works, thanks for the quick fix.
