### ISSUE TITLE
Firefox Wayland, extreme slow performance

### ISSUE THREAD

**Issue by boredsquirrel** [igo95862/bubblejail#139]
### Output of `bubblejail --version`

0.9.3

### Your distro name and version

Fedora Kinoite 40

### Description

The performance is incredibly slow. Not only opening and loading new tabs, but also opening the NoScript overview or doing anything else.

I can try to debug this further. This is what I got for now

```
ExceptionHandler::GenerateDump attempting to generate:/var/home/user/.mozilla/firefox/ARKENFOX/minidumps/618c94a1-c1b5-51db-49f3-3f2f3e96014e.dmp
ExceptionHandler::GenerateDump cloned child 1045
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::GenerateDump minidump generation succeeded
[ERROR crashreporter] exiting with error: Failed to move ⁨/var/home/user/.mozilla/firefox/ARKENFOX/minidumps/618c94a1-c1b5-51db-49f3-3f2f3e96014e.dmp⁩ to ⁨/var/home/user/.mozilla/firefox/Crash Reports/pending/618c94a1-c1b5-51db-49f3-3f2f3e96014e.dmp⁩
Exiting due to channel error.
```

I can attach that dump
[618c94a1-c1b5-51db-49f3-3f2f3e96014e.extra.txt](https://github.com/user-attachments/files/17391040/618c94a1-c1b5-51db-49f3-3f2f3e96014e.extra.txt)

I added the .txt extension for Github to allow it.

These are my configs:

```
services.toml

[common]
executable_name = "/usr/bin/firefox"
share_local_time = false
filter_disk_sync = false
dbus_name = "org.mozilla.*"

[wayland]

[network]

[pulse_audio]

[home_share]
home_paths = [
    "Downloads",
    ".mozilla",
]

[direct_rendering]
enable_aco = false

[notify]

[pipewire]

[v4l]
```

Okay, so I think enabling `enable_aco = true` fixed it!

**Comment by boredsquirrel** [comment]
no that was not the fix. Performance was better but got increasingly worse. 

Feels like memory leakage, may be something else.

In the end it crashed and took the fish shell with it, which I used to spawn the process from the terminal. No error output or crash dialog.

I cannot reproduce as bubblejail thinks the process is still running, while there are no "firefox" or "bubblejail" processes, only a couple of other bwrap processes.

```
bubblejail run firefox firefox                                                                                                                                                                                              ✘ 1 main ◼
Instance already running.
Sending command to the instance:  ['firefox']
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 20, in <module>
    bubblejail_main()
  File "/usr/lib64/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 232, in bubblejail_main
    func(**args_dict)
  File "/usr/lib64/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 83, in run_bjail
    command_return_text = async_run(
                          ^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/bubblejail/python-packages/bubblejail/bubblejail_instance.py", line 152, in send_run_rpc
    (reader, writer) = await open_unix_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/unix_events.py", line 261, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib64/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/selector_events.py", line 659, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

I will try to reproduce this evening

**Comment by igo95862** [comment]
Hello @boredsquirrel 

> Okay, so I think enabling `enable_aco = true` fixed it!

This setting does not do anything and is deprecated. The ACO vulkan compiler is the default on recent mesa version anyway.

**Comment by igo95862** [comment]
```
[home_share]
home_paths = [
    "Downloads",
    ".mozilla",
]
```

I don't recommend sharing the existing `.mozilla` folder. Try running the complete fresh instance without any tweaks to default settings.

**Comment by boredsquirrel** [comment]
hey there! Yes I will try using a vanilla profile.

A few issues are there, I might do some changes to the vanillay config soon.

So far no issues, but firefox doesnt use it's bubblejail home as home, and cannot find `~/.local/share/bubblejail/instances/INTANCE-NAME/home` in the GTK filepicker.

This is a bit odd, maybe a different issue. I will try if I can reproduce the crashy stuff

**Comment by boredsquirrel** [comment]
I tried again with default configs, just pipewire added, no different shared folders

```sh
(org.mozilla.firefox:2): dconf-WARNING **: 15:00:29.555: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[Parent 2, Unnamed thread 7f46f1a2f160] WARNING: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown: 'glib warning', file /builddir/build/BUILD/firefox-132.0/toolkit/xre/nsSigHandlers.cpp:187

(org.mozilla.firefox:2): dconf-WARNING **: 15:00:30.057: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[Parent 2, Unnamed thread 7f46f1a2f160] WARNING: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown: 'glib warning', file /builddir/build/BUILD/firefox-132.0/toolkit/xre/nsSigHandlers.cpp:187

(org.mozilla.firefox:2): dconf-WARNING **: 15:00:30.058: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown


Warning: The program „/bin/fish“ has crashed.

```

**Comment by boredsquirrel** [comment]
I tried again and FF works perfectly. No idea what was the issue. I did a lot of benchmarks, tested permissions etc.
