### ISSUE TITLE
arch chroot build - test_empty_profile fails

### ISSUE THREAD

**Issue by kiasoc5** [igo95862/bubblejail#14]
XDG_RUNTIME_DIR is not present in the chroot.
```
ninja: Entering directory `/build/bubblejail/src/build'
ninja: no work to do.
1/1 unittest FAIL            0.15s   exit status 1
>>> MALLOC_PERTURB_=175 /usr/bin/python3 -m unittest
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
Started unix server
self.terminator_look_for_command:  None
Client connected
Response bytes: b'{"id": "test", "result": ["pong"]}\n'
Terminated
Reached end of reader. Returnning
stderr:
./build/bubblejail/src/test/test_helper.py:35: DeprecationWarning: There is no current event loop
  self.event_loop = get_event_loop()
..E...
======================================================================
ERROR: test_empty_profile (test.test_instance_creation.TestInstanceGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/async_case.py", line 65, in _callTestMethod
    self._callMaybeAsync(method)
  File "/usr/lib/python3.10/unittest/async_case.py", line 88, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/unittest/async_case.py", line 102, in _asyncioLoopRunner
    ret = await awaitable
  File "/build/bubblejail/src/test/test_instance_creation.py", line 41, in test_empty_profile
    new_instance = BubblejailDirectories.create_new_instance(
  File "/build/bubblejail/src/bubblejail/bubblejail_directories.py", line 148, in create_new_instance
    instance = BubblejailInstance(instance_directory)
  File "/build/bubblejail/src/bubblejail/bubblejail_instance.py", line 132, in __init__
    get_runtime_dir() + f'/bubblejail/{self.name}')
  File "/usr/lib/python3.10/site-packages/xdg/BaseDirectory.py", line 127, in get_runtime_dir
    return os.environ['XDG_RUNTIME_DIR']
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_RUNTIME_DIR'

----------------------------------------------------------------------
```

**Comment by igo95862** [comment]
See if the master works now.

**Comment by kiasoc5** [comment]
It works.
