### ISSUE TITLE
[network] gives access to X

### ISSUE THREAD

**Issue by odomingao** [igo95862/bubblejail#145]
### Output of `bubblejail --version`

0.9.3

### Your distro name and version

arch

### Description

Hello!

I noticed that every sandbox can always access X, even when it shouldn't. By creating a new profile, I managed to narrow it down to the [network] permission. Any idea what's going on there, and how I could prevent this from happening?

**Comment by igo95862** [comment]
Hello @odomingao 

This is because of abstract sockets:

https://unix.stackexchange.com/questions/206386/what-does-the-symbol-denote-in-the-beginning-of-a-unix-domain-socket-path-in-l/206395#206395

https://github.com/igo95862/bubblejail/issues/54#issuecomment-1586177545

You have to unshare the network namespace by disabling `[network]` service. You can use the `[slirp4netns]` to provide network access through a proxy.

It might also be possible to disable abstact sockets on the X11 server:

https://unix.stackexchange.com/questions/112316/is-it-possible-to-tell-xorg-not-to-listen-on-the-abstract-socket

**Comment by odomingao** [comment]
Thanks!

Regarding slirp4netns, do I need bubblewrap-suid? I'm getting an error with the following config:

```
[slirp4netns]
dns_servers = [
    "9.9.9.9",
]
outbound_addr = ""
disable_host_loopback = true
```

```
bwrap: Can't create file at /etc/resolv.conf: No such file or directory
/proc/87724/ns/net: No such file or directory
child failed(1)
Traceback (most recent call last):
  File "/usr/lib/bubblejail/python-packages/bubblejail/services.py", line 975, in post_init_hook
    await wait_for(slirp_ready_task, timeout=3)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 20, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 232, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 100, in run_bjail
    async_run(
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_instance.py", line 230, in async_run_init
    bwrap_process = await runner.setup_runtime(exit_stack, args_to_run)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_runner.py", line 485, in setup_runtime
    return await exit_stack.enter_async_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 659, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_runner.py", line 465, in setup_bubblewrap_subprocess
    await self.task_post_init
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_runner.py", line 324, in _run_post_init_hooks
    await hook(sandboxed_pid)
  File "/usr/lib/bubblejail/python-packages/bubblejail/services.py", line 977, in post_init_hook
    raise BubblejailInitializationError("Slirp4netns initialization failed")
bubblejail.exceptions.BubblejailInitializationError: Slirp4netns initialization failed
```

**Comment by igo95862** [comment]
Can you remove the `dns_servers` and `outbound_addr` ? The `dns_servers` setting allows you to override the `/etc/resolv.conf` inside sandbox but it should work fine without it.

**Comment by odomingao** [comment]
Still getting an error:

```
Sandboxed PID: 7263
bwrap: Can't create file at /etc/resolv.conf: No such file or directory
/proc/7263/ns/net: No such file or directory
child failed(1)
Traceback (most recent call last):
  File "/usr/lib/bubblejail/python-packages/bubblejail/services.py", line 975, in post_init_hook
    await wait_for(slirp_ready_task, timeout=3)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 20, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 232, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 100, in run_bjail
    async_run(
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_instance.py", line 230, in async_run_init
    bwrap_process = await runner.setup_runtime(exit_stack, args_to_run)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_runner.py", line 485, in setup_runtime
    return await exit_stack.enter_async_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 659, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_runner.py", line 465, in setup_bubblewrap_subprocess
    await self.task_post_init
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_runner.py", line 324, in _run_post_init_hooks
    await hook(sandboxed_pid)
  File "/usr/lib/bubblejail/python-packages/bubblejail/services.py", line 977, in post_init_hook
    raise BubblejailInitializationError("Slirp4netns initialization failed")
bubblejail.exceptions.BubblejailInitializationError: Slirp4netns initialization failed
```

```
[slirp4netns]
disable_host_loopback = true
```

**Comment by igo95862** [comment]
Hmmm...

Do you actually have a `/etc/resolv.conf` file in your file system?

**Comment by odomingao** [comment]
Yes, it's a symlink to `/run/systemd/resolve/stub-resolv.conf`. I haven't edited it.

**Comment by igo95862** [comment]
This is probably the issue. The bwrap is still using the old mount API that does not handle the symlinks properly.

Can you try passing the `/run/systemd/resolve/stub-resolv.conf` to sandbox using the `[root_share]` service?

**Comment by odomingao** [comment]
still getting an error:

```
Sandboxed PID: 26965
bwrap: Can't create file at /etc/resolv.conf: No such file or directory
sent tapfd=5 for tap0
received tapfd=5
Starting slirp
* MTU:             1500
* Network:         10.0.2.0
* Netmask:         255.255.255.0
* Gateway:         10.0.2.2
* DNS:             10.0.2.3
* DHCP begin:      10.0.2.15
* DHCP end:        10.0.2.30
* Recommended IP:  10.0.2.100
Bubblewrap started. PID: <Process 26964>
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 20, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 232, in bubblejail_main
    func(**args_dict)
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_cli.py", line 100, in run_bjail
    async_run(
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/bubblejail/python-packages/bubblejail/bubblejail_instance.py", line 241, in async_run_init
    raise BubblewrapRunError(
bubblejail.exceptions.BubblewrapRunError: Bubblewrap failed. Try running bubblejail in terminal to see the exact error.
```

**Comment by igo95862** [comment]
I guess it will require some code changes to fix this.

Meanwhile you can try replacing the symlink at `/etc/resolv.conf` with an actual file.

**Comment by odomingao** [comment]
Thanks, replacing the symlink does fix the issue

**Comment by igo95862** [comment]
I will see if I can fix this by overlaying the resolv.conf over the sym linked location.

**Comment by igo95862** [comment]
@odomingao I created a fix for slirp4netns in 9777f9ccf9b3bb370def2479d19d489801007ff2. Can you give it a test?

**Comment by odomingao** [comment]
Thanks. It didn't seem to work, though I didn't reboot. 

I installed bubblejail-git (with a clean build), re-symlinked the file and tried starting a sandbox. Got the same error:

`bwrap: Can't create file at /etc/resolv.conf: No such file or directory`

**Comment by igo95862** [comment]
> I installed bubblejail-git

Did you specify the branch in PKGBUILD? I add this commit to the `slirp4netns-resolv-symlink-fix` branch not master. I think you need to append `#branch=slirp4netns-resolv-symlink-fix` to the `source` entry.

**Comment by odomingao** [comment]
My bad, I appended the correct branch and tested. It appears to be fixed. Thanks!
