### ISSUE TITLE
Error trying to create steam instance.

### ISSUE THREAD

**Issue by y0shir** [igo95862/bubblejail#24]
While trying to create steam profile i got an error:
```
$ bubblejail create --profile steam SteamInstance
Traceback (most recent call last):
  File "/usr/local/bin/bubblejail", line 16, in <module>
    bubblejail_main()
  File "/usr/local/lib/x86_64-linux-gnu/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 363, in bubblejail_main
    args.func(args)
  File "/usr/local/lib/x86_64-linux-gnu/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 256, in bjail_create
    BubblejailDirectories.create_new_instance(
  File "/usr/local/lib/x86_64-linux-gnu/bubblejail/python_packages/bubblejail/bubblejail_directories.py", line 150, in create_new_instance
    profile: BubblejailProfile = cls.profile_get(
  File "/usr/local/lib/x86_64-linux-gnu/bubblejail/python_packages/bubblejail/bubblejail_directories.py", line 110, in profile_get
    return BubblejailProfile(**toml_load(profile_file))
  File "/usr/lib/python3/dist-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/lib/python3/dist-packages/toml/decoder.py", line 186, in loads
    raise TypeError("Expecting something like a string")
TypeError: Expecting something like a string
```

**Comment by igo95862** [comment]
Are you on Debian derivative?

**Comment by codeInTheShell** [comment]
Same issue on Ubuntu when running existing profiles, creating new ones or trying to run newly created ones. Decoder errors are the same the rest varies depending on use case. GUI is no different

**Comment by igo95862** [comment]
Did you install the `tomli` and `tomli-w` packages? `toml` is abandoned and is no longer supported.

**Comment by igo95862** [comment]
You will need Ubuntu 22.04 because `tomli` did not ship before that.

**Comment by codeInTheShell** [comment]
Ok, i wasn't aware of tomli and tomli-w, installing them did resolve throwing errors, the behavior is still "broken" though.

**Comment by igo95862** [comment]
> Ok, i wasn't aware of tomli and tomli-w, installing them did resolve throwing errors, the behavior is still "broken" though.

I am going to remove the `toml` support because it has been causing issues.

**Comment by codeInTheShell** [comment]
Could you update manual installation to include this info as well please?

**Comment by igo95862** [comment]
Yes, I forgot to update it. Thank you for noticing it.
