### ISSUE TITLE
Bubblejail failing to find instance

### ISSUE THREAD

**Issue by Pepperspraylaugh** [igo95862/bubblejail#9]
To keep it short, I tried to make a steam instance, and it failed.

```
sudo bubblejail run Steamiso
Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 10, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 334, in bubblejail_main
    args.func(args)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 63, in run_bjail
    instance = BubblejailDirectories.instance_get(instance_name)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_directories.py", line 88, in instance_get
    raise BubblejailInstanceNotFoundError(instance_name)
bubblejail.exceptions.BubblejailInstanceNotFoundError: Steamiso
```
I don't know what I did wrong, since it just so happened after installing it.

**Comment by igo95862** [comment]
Why are you using `sudo`?

**Comment by Pepperspraylaugh** [comment]
> `sudo` is probably causing this issue.
> 
> bubblejail is **not** a privileged program.

```
bubblejail run Steamiso steam     
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/lib/python3.9/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/lib/python3.9/site-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
  File "/usr/lib/python3.9/site-packages/toml/decoder.py", line 1026, in load_array
    nval, ntype = self.load_value(a[i])
  File "/usr/lib/python3.9/site-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bubblejail", line 10, in <module>
    bubblejail_main()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 334, in bubblejail_main
    args.func(args)
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_cli.py", line 82, in run_bjail
    async_run(
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 264, in async_run_init
    instance_config = self._read_config()
  File "/usr/lib/bubblejail/python_packages/bubblejail/bubblejail_instance.py", line 198, in _read_config
    conf_dict = cast(ServicesConfDictType, toml_loads(config_contents))
  File "/usr/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 20 column 1 char 230)
```

**Comment by igo95862** [comment]
Something is wrong with your TOML files.

**Comment by igo95862** [comment]
@Pepperspraylaugh Any updates?
